# Generated by Django 5.2.6 on 2025-10-17 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoUser',
            fields=[
            ],
            options={
                'verbose_name': 'Médico (Utilizador)',
                'verbose_name_plural': 'Médicos (Utilizadores)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_medico', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('crm', models.CharField(max_length=20, unique=True, verbose_name='CRM')),
                ('especialidade', models.CharField(choices=[('CARDIOLOGIA', 'Cardiologia'), ('DERMATOLOGIA', 'Dermatologia'), ('GINECOLOGIA', 'Ginecologia'), ('ORTOPEDIA', 'Ortopedia'), ('PEDIATRIA', 'Pediatria'), ('CLINICA_GERAL', 'Clínica Geral')], default='CLINICA_GERAL', max_length=50)),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos', to='clinicas.clinica')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
