# Generated by Django 5.2.6 on 2025-10-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_scheduling', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('reminder_hours_before', models.PositiveSmallIntegerField(default=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
