# Generated by Django 5.2.6 on 2025-10-10 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'Login bem-sucedido'), ('CREATE', 'Criação de Objeto'), ('UPDATE', 'Atualização de Objeto'), ('DELETE', 'Remoção de Objeto'), ('PASSWORD_RESET', 'Redefinição de Senha')], max_length=20, verbose_name='Tipo de Ação')),
                ('details', models.TextField(verbose_name='Detalhes')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to=settings.AUTH_USER_MODEL, verbose_name='Ator')),
            ],
            options={
                'verbose_name': 'Registo de Log',
                'verbose_name_plural': 'Registos de Log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
