# Generated by Django 5.2.6 on 2025-10-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dados_clinicos',
            field=models.TextField(blank=True),
        ),
    ]
