# Generated by Django 5.2.6 on 2025-09-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_email_alter_paciente_telefone'),
    ]

    operations = [
    ]
