# Generated by Django 5.2.6 on 2025-09-22 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora da Consulta')),
                ('status_atual', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=50, verbose_name='Status Atual')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Consulta')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='consultas_sediadas', to='clinicas.clinica', verbose_name='Clínica')),
                ('medico', models.ForeignKey(limit_choices_to={'user_type': 'MEDICO'}, on_delete=django.db.models.deletion.RESTRICT, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_agendadas', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agendamentos.consulta', verbose_name='Consulta')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=50, verbose_name='Status do Pagamento')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='ConsultaStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_novo', models.CharField(max_length=50, verbose_name='Novo Status')),
                ('data_modificacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Modificação')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='agendamentos.consulta', verbose_name='Consulta')),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Log de Status da Consulta',
                'verbose_name_plural': 'Logs de Status da Consulta',
            },
        ),
    ]
