# Generated by Django 5.2.6 on 2025-10-17 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora da Consulta')),
                ('status_atual', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('CONCLUIDA', 'Concluída'), ('SOLICITANDO_REAGENDAMENTO', 'Solicitando Reagendamento'), ('REAGENDADA', 'Reagendada')], default='PENDENTE', max_length=50, verbose_name='Status Atual')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Consulta')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_novo', models.CharField(max_length=50, verbose_name='Novo Status')),
                ('data_modificacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Modificação')),
            ],
            options={
                'verbose_name': 'Log de Status da Consulta',
                'verbose_name_plural': 'Logs de Status da Consulta',
            },
        ),
        migrations.CreateModel(
            name='AnotacaoConsulta',
            fields=[
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='anotacao', serialize=False, to='agendamentos.consulta')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da Anotação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anotação de Consulta',
                'verbose_name_plural': 'Anotações de Consulta',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agendamentos.consulta', verbose_name='Consulta')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=50, verbose_name='Status do Pagamento')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
