# Generated by Django 5.2.6 on 2025-10-17 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='consultas_sediadas', to='clinicas.clinica', verbose_name='Clínica'),
        ),
    ]
