# Generated by Django 5.2.6 on 2025-10-17 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0002_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(limit_choices_to={'user_type': 'MEDICO'}, on_delete=django.db.models.deletion.RESTRICT, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Médico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_agendadas', to='pacientes.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='consultastatuslog',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='agendamentos.consulta', verbose_name='Consulta'),
        ),
        migrations.AddField(
            model_name='consultastatuslog',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
    ]
