# Generated by Django 5.2.6 on 2025-10-10 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacaoConsulta',
            fields=[
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='anotacao', serialize=False, to='agendamentos.consulta')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da Anotação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anotação de Consulta',
                'verbose_name_plural': 'Anotações de Consulta',
            },
        ),
    ]
