# Generated by Django 5.2.6 on 2025-10-17 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretariaUser',
            fields=[
            ],
            options={
                'verbose_name': 'Secretária (Utilizador)',
                'verbose_name_plural': 'Secretárias (Utilizadores)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_secretaria', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secretarias', to='clinicas.clinica')),
            ],
            options={
                'verbose_name': 'Secretária',
                'verbose_name_plural': 'Secretárias',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
