# Generated by Django 5.2.6 on 2025-10-10 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0002_initial'),
        ('secretarias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaria',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secretarias', to='clinicas.clinica'),
        ),
    ]
