# Generated by Django 5.2.6 on 2025-10-17 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinicas_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinicas.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='tipo_clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinicas.tipoclinica', verbose_name='Tipo de Clínica'),
        ),
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together={('nome', 'estado')},
        ),
    ]
